version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./tools/docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    links:
      - db
      - mail
      - redis
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: serverName=grafikart
  node:
    build:
      context: ./tools/docker/node
    command: yarn run dev-server
    working_dir: /usr/src/app
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: grafikart
      POSTGRES_USER: grafikart
      POSTGRES_DB: grafikart
    ports:
      - 5432:5432 # On expose le port pour pouvoir inspecter la base pendant la phase de développement
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    links:
      - db
    ports:
      - 8888:8080
  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  spacechop:
    image: spacechop/spacechop:latest
    volumes:
      - ./spacechop.yml:/config.yml
      - ./public/uploads:/mnt/images/uploads
  redis:
    image: redis:5-alpine


volumes:
  db-data:
    driver: local
