version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    links:
      - db
      - dbtest
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: grafikart
      POSTGRES_USER: grafikart
      POSTGRES_DB: grafikart
    ports:
      - 5432:5432 # On expose le port pour pouvoir inspecter la base pendant la phase de développement
    volumes:
      - db-data:/var/lib/postgresql/data
  dbtest:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: 'arcs-material'
    links:
      - db
    ports:
      - 8888:8080
  mail:
    image: djfarrelly/maildev
    ports:
      - 1080:80

volumes:
  db-data:
    driver: local
