parameters:
  admin_prefix: '%env(resolve:ADMIN_PREFIX)%'
  download_path: '%kernel.project_dir%/downloads'
  videos_path: '%download_path%/videos'
  sources_path: '%download_path%/sources'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    App\Http\Admin\Controller\:
      resource: '../src/Http/Admin/Controller'
      tags: ['controller.service_arguments']

    Google_Service_YouTube_Resource_PlaylistItems:
        class: '\Google_Service_YouTube_Resource_PlaylistItems'
        factory: ['App\Services\Api\GoogleServiceFactory', 'createPlaylistItems']
        arguments: ['@Google_Client']

    Everyman\Neo4j\Client:
      class: 'Everyman\Neo4j\Client'
      factory: ['App\Services\Neo4jClientFactory', 'createClient']
      arguments: ['neo4j', 'neo4j', 'neo4j']

    App\Infrastructure\Storage\Naming\IdDirectoryNamer:
      class: App\Infrastructure\Storage\Naming\IdDirectoryNamer
      public: true

    App\Http\Admin\Firewall\AdminRequestListener:
      class: App\Http\Admin\Firewall\AdminRequestListener
      arguments: ['%admin_prefix%']

    Knp\Bundle\PaginatorBundle\Helper\Processor:
      class: Knp\Bundle\PaginatorBundle\Helper\Processor

    App\Helper\Paginator\PaginatorInterface:
      class: App\Helper\Paginator\KnpPaginator
