services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Google_Service_YouTube_Resource_PlaylistItems:
        class: '\Google_Service_YouTube_Resource_PlaylistItems'
        factory: ['App\Services\Api\GoogleServiceFactory', 'createPlaylistItems']
        arguments: ['@Google_Client']
