doctrine:
  orm:
    mappings:
      App\Live:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Live'
        prefix: 'App\Domains\Live'
        alias: App\Domains\Live
