doctrine:
  orm:
    mappings:
      App\Domain\Live:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Domain/Live'
        prefix: 'App\Domain\Live'
        alias: App\Domain\Live
