services:
  \Google_Service_YouTube_Resource_PlaylistItems:
    class: '\Google_Service_YouTube_Resource_PlaylistItems'
    factory: ['App\Services\Api\GoogleServiceFactory', 'createPlaylistItems']
  App\Domain\Live\LiveSyncService:
    arguments:
      $playlistID: '%app.live_playlist%'

doctrine:
  orm:
    mappings:
      App\Domain\Live:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Domain/Live'
        prefix: 'App\Domain\Live'
        alias: App\Domain\Live
